import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "blipppppppppppppp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const numDots = 829;
  const dots = [];
  let color = "white";
  for (let i = 0; i < numDots; i++) {
      // note: we are adding a key prop here to allow react to uniquely identify each
      // element in this array. see: https://reactjs.org/docs/lists-and-keys.html
      if (Math.random() < 0.3)
        color = `black`;
      else
        color = "white";
      dots.push(<div key={i} className="circle" style={{backgroundColor: color}}></div>);
  }

  return (
    <html lang="en">
      <body style={{opacity: "0"}}>
        <div className="parent">
            {children}
        </div>
      </body>
    </html>
  );
}
