import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "blipppppppppppppp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body style={{opacity: "0"}}>
      <div className="parent">
          {children}
      </div>
      </body>
    </html>
  );
}
